import { trackSelfDescribingEvent, CommonEventProperties, SelfDescribingJson } from '@snowplow/browser-tracker';
import * as Ecom from '@snowplow/browser-plugin-snowplow-ecommerce';
// Automatically generated by Snowtype

type SnowplowEcommerceAction = any;

type Promotion = any;

type Product = any;

type Cart = any;

type TransactionError = any;

type Transaction = any;

type Refund = any;

type CheckoutStep = any;

/**
 * Creates a Snowplow Event Specification entity.
 */
export function createEventSpecification(eventSpecification: EventSpecification){
    return {
        schema:
            'iglu:com.snowplowanalytics.snowplow/event_specification/jsonschema/1-0-2',
        data: eventSpecification,
    }
}

/**
 * Automatically attached context for event specifications
 */
interface EventSpecification {
    id: string;
    name: string;
    data_product_id: string;
    data_product_name: string;
}



/**
 * Tracks a InternalPromotionView event specification.
 * ID: 0290c4fe-b34a-43f3-a588-92fb8d98795d
 */
export function trackInternalPromotionViewSpec(internalPromotionView: Ecom.SPPromotion & Ecom.CommonEcommerceEventProperties, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '0290c4fe-b34a-43f3-a588-92fb8d98795d',
        name: 'Internal promotion view',
        data_product_id: '04080f2e-24c3-46dd-9e0f-a9631968b872',
        data_product_name: 'E-commerce Web'
    });

    const context = Array.isArray(internalPromotionView.context)
        ? [...internalPromotionView.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedInternalPromotionView = {
        ...internalPromotionView,
        context: context as unknown as SelfDescribingJson<Record<string, unknown>>[],
    };

    Ecom.trackPromotionView(modifiedInternalPromotionView, trackers);
}
/**
 * Tracks a RemoveFromCart event specification.
 * ID: 1613be8f-61fe-46a3-8ec2-5e4bf5d6c322
 */
export function trackRemoveFromCartSpec(removeFromCart: Ecom.Cart & Ecom.CommonEcommerceEventProperties, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '1613be8f-61fe-46a3-8ec2-5e4bf5d6c322',
        name: 'Remove from cart',
        data_product_id: '04080f2e-24c3-46dd-9e0f-a9631968b872',
        data_product_name: 'E-commerce Web'
    });

    const context = Array.isArray(removeFromCart.context)
        ? [...removeFromCart.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedRemoveFromCart = {
        ...removeFromCart,
        context: context as unknown as SelfDescribingJson<Record<string, unknown>>[],
    };

    Ecom.trackRemoveFromCart(modifiedRemoveFromCart, trackers);
}
/**
 * Tracks a ProductListClick event specification.
 * ID: 1df3e940-bd02-4e62-a569-888c67764ae0
 */
export function trackProductListClickSpec(productListClick: Ecom.ListClickEvent & Ecom.CommonEcommerceEventProperties, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '1df3e940-bd02-4e62-a569-888c67764ae0',
        name: 'Product list click',
        data_product_id: '04080f2e-24c3-46dd-9e0f-a9631968b872',
        data_product_name: 'E-commerce Web'
    });

    const context = Array.isArray(productListClick.context)
        ? [...productListClick.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedProductListClick = {
        ...productListClick,
        context: context as unknown as SelfDescribingJson<Record<string, unknown>>[],
    };

    Ecom.trackProductListClick(modifiedProductListClick, trackers);
}
/**
 * Tracks a InternalPromotionClick event specification.
 * ID: 46b6ab9b-8d62-4b57-9716-3c35f63b3a69
 */
export function trackInternalPromotionClickSpec(internalPromotionClick: Ecom.SPPromotion & Ecom.CommonEcommerceEventProperties, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '46b6ab9b-8d62-4b57-9716-3c35f63b3a69',
        name: 'Internal promotion click',
        data_product_id: '04080f2e-24c3-46dd-9e0f-a9631968b872',
        data_product_name: 'E-commerce Web'
    });

    const context = Array.isArray(internalPromotionClick.context)
        ? [...internalPromotionClick.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedInternalPromotionClick = {
        ...internalPromotionClick,
        context: context as unknown as SelfDescribingJson<Record<string, unknown>>[],
    };

    Ecom.trackPromotionClick(modifiedInternalPromotionClick, trackers);
}
/**
 * Tracks a TransactionError event specification.
 * ID: 49121b77-bb70-472c-af8c-d55d059fad38
 */
export function trackTransactionErrorSpec(transactionError: Ecom.TransactionError & Ecom.CommonEcommerceEventProperties, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '49121b77-bb70-472c-af8c-d55d059fad38',
        name: 'Transaction Error',
        data_product_id: '04080f2e-24c3-46dd-9e0f-a9631968b872',
        data_product_name: 'E-commerce Web'
    });

    const context = Array.isArray(transactionError.context)
        ? [...transactionError.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedTransactionError = {
        ...transactionError,
        context: context as unknown as SelfDescribingJson<Record<string, unknown>>[],
    };

    Ecom.trackTransactionError(modifiedTransactionError, trackers);
}
/**
 * Tracks a Transaction event specification.
 * ID: 4f754652-4452-43f1-a290-672a5de105da
 */
export function trackTransactionSpec(transaction: Ecom.SPTransaction & Ecom.CommonEcommerceEventProperties, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '4f754652-4452-43f1-a290-672a5de105da',
        name: 'Transaction',
        data_product_id: '04080f2e-24c3-46dd-9e0f-a9631968b872',
        data_product_name: 'E-commerce Web'
    });

    const context = Array.isArray(transaction.context)
        ? [...transaction.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedTransaction = {
        ...transaction,
        context: context as unknown as SelfDescribingJson<Record<string, unknown>>[],
    };

    Ecom.trackTransaction(modifiedTransaction, trackers);
}
/**
 * Tracks a TrackProductView event specification.
 * ID: 558d3a23-0dc6-4b9f-9d77-93f255404cdb
 */
export function trackTrackProductViewSpec(trackProductView: Ecom.Product & Ecom.CommonEcommerceEventProperties, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '558d3a23-0dc6-4b9f-9d77-93f255404cdb',
        name: 'Track product view',
        data_product_id: '04080f2e-24c3-46dd-9e0f-a9631968b872',
        data_product_name: 'E-commerce Web'
    });

    const context = Array.isArray(trackProductView.context)
        ? [...trackProductView.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedTrackProductView = {
        ...trackProductView,
        context: context as unknown as SelfDescribingJson<Record<string, unknown>>[],
    };

    Ecom.trackProductView(modifiedTrackProductView, trackers);
}
/**
 * Tracks a Refund event specification.
 * ID: 8688073f-e51a-4b64-83cd-567aa058a497
 */
export function trackRefundSpec(refund: Ecom.Refund & Ecom.CommonEcommerceEventProperties, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '8688073f-e51a-4b64-83cd-567aa058a497',
        name: 'Refund',
        data_product_id: '04080f2e-24c3-46dd-9e0f-a9631968b872',
        data_product_name: 'E-commerce Web'
    });

    const context = Array.isArray(refund.context)
        ? [...refund.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedRefund = {
        ...refund,
        context: context as unknown as SelfDescribingJson<Record<string, unknown>>[],
    };

    Ecom.trackRefund(modifiedRefund, trackers);
}
/**
 * Tracks a AddToCart event specification.
 * ID: a0a29c1a-2275-4845-9df2-4800204f6dcf
 */
export function trackAddToCartSpec(addToCart: Ecom.Cart & Ecom.CommonEcommerceEventProperties, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: 'a0a29c1a-2275-4845-9df2-4800204f6dcf',
        name: 'Add to cart',
        data_product_id: '04080f2e-24c3-46dd-9e0f-a9631968b872',
        data_product_name: 'E-commerce Web'
    });

    const context = Array.isArray(addToCart.context)
        ? [...addToCart.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedAddToCart = {
        ...addToCart,
        context: context as unknown as SelfDescribingJson<Record<string, unknown>>[],
    };

    Ecom.trackAddToCart(modifiedAddToCart, trackers);
}
/**
 * Tracks a CheckoutStep event specification.
 * ID: a5b4eecb-9e9c-465b-84b6-ebc1d6231134
 */
export function trackCheckoutStepSpec(checkoutStep: Ecom.CheckoutStep & Ecom.CommonEcommerceEventProperties, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: 'a5b4eecb-9e9c-465b-84b6-ebc1d6231134',
        name: 'Checkout step',
        data_product_id: '04080f2e-24c3-46dd-9e0f-a9631968b872',
        data_product_name: 'E-commerce Web'
    });

    const context = Array.isArray(checkoutStep.context)
        ? [...checkoutStep.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedCheckoutStep = {
        ...checkoutStep,
        context: context as unknown as SelfDescribingJson<Record<string, unknown>>[],
    };

    Ecom.trackCheckoutStep(modifiedCheckoutStep, trackers);
}
/**
 * Tracks a ProductListView event specification.
 * ID: f175fb64-14a0-4638-9de2-e4d3cee4399f
 */
export function trackProductListViewSpec(productListView: Ecom.ListViewEvent & Ecom.CommonEcommerceEventProperties, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: 'f175fb64-14a0-4638-9de2-e4d3cee4399f',
        name: 'Product list view',
        data_product_id: '04080f2e-24c3-46dd-9e0f-a9631968b872',
        data_product_name: 'E-commerce Web'
    });

    const context = Array.isArray(productListView.context)
        ? [...productListView.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedProductListView = {
        ...productListView,
        context: context as unknown as SelfDescribingJson<Record<string, unknown>>[],
    };

    Ecom.trackProductListView(modifiedProductListView, trackers);
}

